import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { IBM_Plex_Sans } from "next/font/google";
import "@/lib/gsap-init";
import InnerHeader from "@/components/inner-header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      <InnerHeader />
      {children}
    </div>
  );
}
