import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { IBM_Plex_Sans } from "next/font/google";

import TopHeader from "@/components/topHeader";
import Script from "next/script";
import Footer from "@/components/footer";
import SmoothScrollProvider from "@/lib/smoothScrollProvider";
import "@/lib/gsap-init";
import InnerHeader from "@/components/inner-header";
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      <InnerHeader />
      {/* <SmoothScrollProvider> */}
      {children}
      {/* </SmoothScrollProvider> */}
      {/* <Footer /> */}
    </div>
  );
}
