import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { IBM_Plex_Sans } from "next/font/google";

import "./globals.css";
import TopHeader from "@/components/topHeader";
import Script from "next/script";
import Footer from "@/components/footer";
import SmoothScrollProvider from "@/lib/smoothScrollProvider";
import "@/lib/gsap-init";
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          src="https://unpkg.com/@splinetool/viewer@1.10.90/build/spline-viewer.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${ibmPlexSans.className} antialiased`}>
        {/* <SmoothScrollProvider> */}
        {children}
        {/* </SmoothScrollProvider> */}
        <Footer />
      </body>
    </html>
  );
}
